/*
	Script for generate colors palette and scss files from a JSON.
	You only need to modify JSON file at /src/lib/__core__/JSON/colors.json, and thats all.
*/

const fs = require('fs');
const colors = require('../src/lib/__core__/JSON/colors.json');


const generateSass = () => {
	let contentPalette = '';
	let contentThemes = '';

	const importVars = `@use 'styles/vars/palette' as *;\n\n`;
	const sassAdvice = '// THIS FILE IS AUTOGENERATED, PLEASE DONT MODIFY\n';

	let sassPalette = "/* Variables por tema */\n";
	let sassThemes = "/* Clases por tema */\n";


	for (const theme in colors) {
		sassPalette += `//#region theme ${theme}\n`;
		for (const key in colors[theme]) {
			if (colors[theme][key]) {
				sassPalette += `$${theme !== 'palette' ? `${theme}-` : ''}${key}: ${colors[theme][key]};\n`;
			};
		};
		sassPalette += `//#endregion \n\n`;


		if (theme === 'light' || theme === 'dark') {
			sassThemes += `//#region theme ${theme}\n`;
			sassThemes += `.theme-${theme} {\n`;

			for (const key in colors[theme]) {
				if (colors[theme][key] && theme !== 'palette') {
					sassThemes += `\t--${key}: #{$${theme}-${key}};\n`;
				}
			};

			sassThemes += `}\n\n`;
			sassThemes += `//#endregion \n\n`;
		};
	}

	contentPalette = `${sassAdvice}${sassPalette}`;
	contentThemes = `${sassAdvice}${importVars}${sassThemes}`;

	fs.writeFileSync('./src/styles/vars/_palette.scss', contentPalette, 'utf8');
	fs.writeFileSync('./src/styles/themes.scss', contentThemes, 'utf8');
	console.log('✅ Archivo _palette.scss y _themes.scss generado correctamente.');
};


generateSass();